nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  awesome.me:
    npmRegistryServer: "https://npm.fontawesome.com"
    npmAuthToken: "${FONT_AWESOME_TOKEN}"
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com"
    npmAuthToken: "${FONT_AWESOME_TOKEN}"
