files:
  - source: /src/locales/en/messages.po
    translation: /src/locales/%two_letters_code%/%original_file_name%
  - source: /textit/eng/gce_letter_confirmation.eng.po
    translation: /textit/%three_letters_code%/gce_letter_confirmation.%three_letters_code%.po
  - source: /textit/eng/gce_letter_deliveredresponse.eng.po
    translation: /textit/%three_letters_code%/gce_letter_deliveredresponse.%three_letters_code%.po
  - source: /textit/eng/gce_letter_feedback.eng.po
    translation: /textit/%three_letters_code%/gce_letter_feedback.%three_letters_code%.po
  - source: /textit/eng/gce_letter_re_check_for_response.eng.po
    translation: /textit/%three_letters_code%/gce_letter_re_check_for_response.%three_letters_code%.po
  - source: /textit/eng/gce_letter_resolution.eng.po
    translation: /textit/%three_letters_code%/gce_letter_resolution.%three_letters_code%.po
  - source: /textit/eng/gce_letter_working_on_resolution.eng.po
    translation: /textit/%three_letters_code%/gce_letter_working_on_resolution.%three_letters_code%.po
